apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2  # 원하는 파드 복제본 수 (기본값: 1)
  selector:
    matchLabels:
      app: community-service  # 템플릿의 labels와 일치해야 함
  template:
    metadata:
      labels:
        app: community-service  # selector와 일치해야 함
    spec:
      containers:
      - name: community-service
        image: suhyunkim7288/community-service:0.0.5
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
        ports:
        - containerPort: 8080

        livenessProbe:
          httpGet:
            path: /api/community/v1/k8s/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 3

        readinessProbe:
          httpGet:
            path: /api/community/v1/k8s/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3

        volumeMounts:
          - mountPath: /etc/config
            name: community-service-config-volume
          - mountPath: /etc/secret
            name: community-service-secret-volume

      volumes:
        - name: community-service-config-volume
          configMap:
            name: community-service-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: community-service-secret-volume
          secret:
            secretName: community-service-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml