apiVersion: v1
kind: Service
metadata:
  name: community-service-mysql-service
spec:
  ports:
    - port: 3306

---

apiVersion: v1
kind: Endpoints
metadata:
  name: community-service-mysql-service
subsets:
  - addresses:
      - ip: 192.168.45.225
    ports:
      - port: 13308