apiVersion: v1
kind: Service
metadata:
  name: community-service-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: community-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
