apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  application-dev.yml: |
    server:
      port: 8080

    spring:
      cloud:
        gateway:
          server:
            webmvc:
              routes:
                - id: test-service
                  uri: http://test-service-service:8080
                  predicates:
                    - Path=/api/test/**
                  filters:
                    - AddAuthenticationHeader

                - id: community-post
                  uri: http://community-service-service:8080
                  predicates:
                    - Path=/api/post/v1/**
                  filters:
                    - AddAuthenticationHeader

                - id: community-like
                  uri: http://community-service-service:8080
                  predicates:
                    - Path=/api/like/v1/**
                  filters:
                    - AddAuthenticationHeader

                - id: community-comment
                  uri: http://community-service-service:8080
                  predicates:
                    - Path=/api/comment/v1/**
                  filters:
                    - AddAuthenticationHeader

                - id: answer-service
                  uri: http://qna-service-service:8080
                  predicates:
                    - Path=/api/answer/v1/**
                  filters:
                    - AddAuthenticationHeader

                - id: question-service
                  uri: http://qna-service-service:8080
                  predicates:
                    - Path=/api/question/v1/**
                  filters:
                    - AddAuthenticationHeader

                - id: user-service
                  uri: http://auth-service-service:8080
                  predicates:
                    - Path=/user/**
                  filters:
                    - AddAuthenticationHeader

                - id: auth-service
                  uri: http://auth-service-service:8080
                  predicates:
                    - Path=/auth/**
                  filters:
                    - AddAuthenticationHeader