apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  application-dev.yml: |
    server:
      port: 8080

    logging:
      level:
        org.springframework.cloud.gateway: DEBUG
        reactor.netty: DEBUG
        org.springframework.http.server.reactive: DEBUG

    spring:
      cloud:
        gateway:
          server:
            webmvc:
              routes:
                - id: test-service
                  uri: http://test-service-service:8080
                  predicates:
                    - Path=/api/test/**
                  filters:
                    - AddAuthenticationHeader

                - id: community-post
                  uri: http://community-service-service:8080
                  predicates:
                    - Path=/api/post/v1/**
                  filters:
                    - AddAuthenticationHeader

                - id: community-like
                  uri: http://community-service-service:8080
                  predicates:
                    - Path=/api/like/v1/**
                  filters:
                    - AddAuthenticationHeader

                - id: community-comment
                  uri: http://community-service-service:8080
                  predicates:
                    - Path=/api/comment/v1/**
                  filters:
                    - AddAuthenticationHeader