apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  application-dev.yml: |
    server:
      port: 8080
    
    spring:
      cloud:
        gateway:
          mvc:
            routes:
              - id: community-service
                uri: http://community-service:8080
                predicates:
                  - Path=/comm/**
