apiVersion: v1
kind: ConfigMap
metadata:
  name: qna-service-config
data:
  application-dev.yml: |
    server:
      port: 8080

    spring:
      datasource:
        url: jdbc:mysql://qna-service-mysql-service:3306/qna?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
          validation-timeout: 5000

      jpa:
        hibernate:
          ddl-auto: create # 오직 테스트 환경에서만
        generate-ddl: true # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
        show-sql: true
        open-in-view: false
        
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: TRACE