apiVersion: v1
kind: Service
metadata:
  name: auth-service-mysql-service
spec:
  ports:
    - port: 3306

---

apiVersion: v1
kind: Endpoints
metadata:
  name: auth-service-mysql-service
subsets:
  - addresses:
      - ip: 192.168.0.97
    ports:
      - port: 13307