apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
stringData:
  application-secret.yml: |
    spring:
      datasource:
        username: user
        password: 1234
      
      cloud:
        aws:
          region:
            static: ap-northeast-2
          s3:
            bucket: csrrr-profile-image
            enabled: true
    
      data:
        redis:
          host: localhost
          port: 6379
