apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  application-dev.yml: |
    server:
      port: 8080

    spring:
      datasource:
        url:
          jdbc:mysql://auth-service-mysql-service:auth?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
          validation-timeout: 5000
    
      jpa:
        hibernate:
          ddl-auto: create # 오직 테스트 환경에서만
        generate-ddl: true # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
        show-sql: true
        open-in-view: false
        
      cloud:
        aws:
          s3:
            enabled: true
    
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
    
      data:
        redis:
          host: localhost
          port: 6379
    
      jwt:
        access-expires-in: 3600 # access token 만료(초)
        refresh-expires-in: 604800 # refresh token 만료(초)
        secret-key: ${JWT_SECRET_KEY}